#!/bin/sh

# BBCLOUD - 2 WAY SMS COMMUNICATIONS FOR BBCLOUD
# INSTALL THIS AS ext/pg/sms
# USE IT AS bbsms-3053900888 
# IT WILL SEND A TEXT MESSAGE - YOU CAN REPLY AND IT WILL ACK

# SERVER SIDE LIVES AT 
#	http://vip.bb4.org/bbsms.php SENDING
# 	http://vip.bb4.org/bback.php ACKING

# if [ "$BBTMP" = "" ]
# then
	# echo "BB environment not set !!!"
	# exit 1
# fi

if ! test "$BBWEBHOST"
then
	BBWEBHOST="BBWEBHOST not set";
fi

# THIS WORKS BUT WILL NEED MSG URL-ENCODED
# curl http://vip.bb4.org/bbsms.php?tel=$TEL\&site=$SITE\&msg=$MSG

echo "$BBALPHAMSG" > /tmp/BBALPHA.$$

SEE=`grep Please /tmp/BBALPHA.$$`

rm -f /tmp/BBALPHA.$$

MSG="$BBHOSTSVC $BBCOLORLEVEL
$SEE"

MSG=$(echo "$MSG" | sed -e 's/%/%25/g' -e 's/ /%20/g' -e 's/!/%21/g' -e 's/"/%22/g' -e 's/#/%23/g' -e 's/\$/%24/g' -e 's/\&/%26/g' -e 's/'\''/%27/g' -e 's/(/%28/g' -e 's/)/%29/g' -e 's/\*/%2a/g' -e 's/+/%2b/g' -e 's/,/%2c/g' -e 's/-/%2d/g' -e 's/\./%2e/g' -e 's/\//%2f/g' -e 's/:/%3a/g' -e 's/;/%3b/g' -e 's//%3e/g' -e 's/?/%3f/g' -e 's/@/%40/g' -e 's/\[/%5b/g' -e 's/\\/%5c/g' -e 's/\]/%5d/g' -e 's/\^/%5e/g' -e 's/_/%5f/g' -e 's/`/%60/g' -e 's/{/%7b/g' -e 's/|/%7c/g' -e 's/}/%7d/g' -e 's/~/%7e/g')


echo curl -s http://vip.bb4.org/bbsms.php --data-urlencode "tel=$RCPT" --data-urlencode "site=$BBWEBHOST" --data-urlencode "ack=$ACKCODE" --data "msg=$MSG"
curl -s http://vip.bb4.org/bbsms.php --data-urlencode "tel=$RCPT" --data-urlencode "site=$BBWEBHOST" --data-urlencode "ack=$ACKCODE" --data-urlencode "msg=$MSG"

exit 0
